[package]
authors = ["Antti Ker√§nen <detegr@gmail.com>"]
name = "velo-backend"
version = "0.1.0"

[dependencies]
chrono = "0.3.1"
diesel = {version = "0.13.0", features = ["sqlite"]}
diesel_codegen = {version = "0.13.0", features = ["sqlite"]}
lazy_static = "0.2.8"
r2d2 = "0.7.2"
r2d2-diesel = "0.13.0"
regex = "0.2.2"
rocket = "0.2.6"
rocket_codegen = "0.2.6"
